[package]
name = "bevy_lospec"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Johan Helsing <johanhelsing@gmail.com>"]
description = "Asset loader plugin for Bevy that adds support for lospec color palettes"
keywords = ["gamedev", "bevy", "palette"]
categories = ["game-development", "rendering", "graphics"]
repository = "https://github.com/johanhelsing/bevy_lospec"

[dependencies]
bevy = "0.7"
serde = "1.0"
serde_json = "1.0"
anyhow = "1.0"